project:
  type: website
  output-dir: docs

website:
  title: "Datos de Elevación con R"
  search: 
    location: navbar
    type: textbox
  navbar:
    title: false
    logo: "img/dibujo_labsaf_color.svg"
    background: "#c3e3cb"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: share

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

